/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-02-24 21:20:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.Tweet;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.test1.stores.*;
import java.util.*;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;



UserStore logged_in_user = new UserStore();
if((Boolean)request.getAttribute("logged_in")) {
	logged_in_user = (UserStore)request.getAttribute("logged_in_user");
}

String viewing_user_tweets_username = (String)request.getAttribute("viewing_user_tweets_username");
String viewing_specific_tweet_uuid = (String)request.getAttribute("viewing_specific_tweet_uuid");


      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if lt IE 7]>\t\t\t<html class=\"no-js lt-ie9 lt-ie8 lt-ie7\"> <![endif]-->\r\n");
      out.write("<!--[if IE 7]>\t\t\t\t <html class=\"no-js lt-ie9 lt-ie8\"> <![endif]-->\r\n");
      out.write("<!--[if IE 8]>\t\t\t\t <html class=\"no-js lt-ie9\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!--> <html class=\"no-js\"> <!--<![endif]-->\r\n");
      out.write("\t\t<head>\r\n");
      out.write("\t\t\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\t\t\t\t<title>Vomitorium</title>\r\n");
      out.write("\t\t\t\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t\t\t\t<meta name=\"viewport\" content=\"width=device-width\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" href=\"/test1/css/bootstrap.min.css\">\r\n");
      out.write("\t\t\t\t<style>\r\n");
      out.write("\t\t\t\t\t\tbody {\r\n");
      out.write("\t\t\t\t\t\t\t\tpadding-top: 50px;\r\n");
      out.write("\t\t\t\t\t\t\t\tpadding-bottom: 20px;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t</style>\r\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" href=\"/test1/css/bootstrap-theme.min.css\">\r\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" href=\"/test1/css/main.css\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<script src=\"/test1/js/libs/modernizr-2.6.2-respond-1.1.0.min.js\"></script>\r\n");
      out.write("\t\t</head>\r\n");
      out.write("\t\t<body>\r\n");
      out.write("\t\t\t\t<!--[if lt IE 7]>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"chromeframe\">You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browser</a> or <a href=\"http://www.google.com/chromeframe/?redirect=true\">activate Google Chrome Frame</a> to improve your experience.</p>\r\n");
      out.write("\t\t\t\t<![endif]-->\r\n");
      out.write("\t<div class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"/test1/Tweet/\">Vomitorium</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t");
/*
						<li class="active"><a href="#">Home</a></li>
						<%/*
						<li><a href="#about">About</a></li>
						<li><a href="#contact">Contact</a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li class="divider"></li>
								<li class="dropdown-header">Nav header</li>
								<li><a href="#">Separated link</a></li>
								<li><a href="#">One more separated link</a></li>
							</ul>
						</li>
						*/ 
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t");

					if((Boolean)request.getAttribute("logged_in")) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"navbar-right\" style=\"color:white\">\r\n");
      out.write("\t\t\t\t\t\t\tHi ");
      out.print(logged_in_user.getUser() );
      out.write("!\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;|&nbsp;<a href=\"/test1/User/logout\">Logout</a>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t");

					} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<form class=\"navbar-form navbar-right\" method=\"post\" action=\"/test1/User/login\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"email\" placeholder=\"Email\" name=\"email\" class=\"form-control\" required>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" placeholder=\"Password\" name=\"password\" class=\"form-control\" required>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-success\">Sign in</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t");

					}
					
      out.write("\r\n");
      out.write("\t\t\t\t</div><!--/.navbar-collapse -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t<!-- Main jumbotron for a primary marketing message or call to action -->\r\n");
      out.write("\t\t<div class=\"jumbotron banner\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t");

					if((Boolean)request.getAttribute("logged_in") == false) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Register</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<form method=\"post\" action=\"/test1/User/add\">\r\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-bottom: 10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <input type=\"text\" class=\"form-control\" placeholder=\"username\" name=\"username\" required/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-bottom: 10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <input type=\"email\" class=\"form-control\" placeholder=\"email\" name=\"email\" required/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-bottom: 5px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <input type=\"password\" class=\"form-control\" placeholder=\"password\" name=\"password\" required/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <input type=\"submit\" value=\"Register\" class=\"btn btn-primary\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");

					}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t");

					if(viewing_user_tweets_username == null || viewing_user_tweets_username.equals("null") || viewing_user_tweets_username.isEmpty()) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Welcome all!</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Ever wanted to vent every single thought out somewhere in naive hope someone is listening? You've come to the right place!</p> \r\n");
      out.write("\t\t\t\t\t\t\t");
/*<p><a class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*/
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");

					} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>");
      out.print(viewing_user_tweets_username);
      out.write(" Tweets!</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>See what he has to say!</p> \r\n");
      out.write("\t\t\t\t\t\t\t<p><a href=\"/test1/User/subscribe?user=");
      out.print(viewing_user_tweets_username);
      out.write("\" class=\"btn btn-primary btn-lg\">Subscribe</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");

					}
					
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t");

			if((Boolean)request.getAttribute("logged_in")) {
			
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 panel panel-default sidebar\">\r\n");
      out.write("\t\t\t\t\t");

					if(viewing_specific_tweet_uuid == null || viewing_specific_tweet_uuid.equals("null") || viewing_specific_tweet_uuid.isEmpty()) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\"><h4>Empart thy knowledge!</h4></div>\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t<form class=\"easy-form-spout\" method=\"post\" action=\"/test1/Tweet\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<textarea name=\"spout\" class=\"form-control easy-form-spout-textarea\" placeholder=\"Type something…\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"help-block\">140</span>\r\n");
      out.write("\t\t\t\t\t\t\t<img style=\"display:none\" class=\"easy-form-spout-loader\" src=\"/test1/images/loading.gif\" alt=\"Loading\" />\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary easy-form-spout-btn\">Spout</button>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t");

					}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<h2>Heading</h2>\r\n");
      out.write("\t\t\t\t\t<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>\r\n");
      out.write("\t\t\t\t\t<p><a class=\"btn btn-default\" href=\"#\">View details &raquo;</a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-9 tweet-list-continer\">\r\n");
      out.write("\t\t\t\t\t");

					System.out.println("In render!");
					List<TweetStore> lTweet = (List<TweetStore>)request.getAttribute("Tweets");
					if (lTweet==null){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p>No Tweet found</p>\r\n");
      out.write("\t\t\t\t\t\t");
 
					}else{
						Iterator<TweetStore> iterator;
						iterator = lTweet.iterator();		 
						while (iterator.hasNext()){
							TweetStore ts = (TweetStore)iterator.next();
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel panel-default\" data-timeuuid=\"");
      out.print(ts.getTimeuuid() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4><a href=\"/test1/Tweet/");
      out.print(ts.getTimeuuid() );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(ts.getTweet() );
      out.write("</a></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"help-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tby <span class=\"user\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"/test1/Tweet/");
      out.print(ts.getUser() );
      out.write("\" title=\"");
      out.print(ts.getUser() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(ts.getUser() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> ~ \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"tweetTime\" data-tweet-time=\"");
      out.print(ts.getTweetTimeJSReadable());
      out.write('"');
      out.write('>');
      out.print(ts.getTweetTime());
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										if ( ts.getUser().equals(logged_in_user.getUser()) ) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form method=\"delete\" action=\"/test1/Tweet/delete\" class=\"delete-tweet-form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(ts.getTimeuuid() );
      out.write("\" name=\"tweet_uuid\" class=\"tweet_uuid\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"delete\" class=\"delete-tweet-btn\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
					}
					
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr>\t\r\n");
      out.write("\t\t");

		}
		
      out.write("\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t<p>Created by Rihards Silins</p>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div> <!-- /container -->\r\n");
      out.write("\t<input type=\"hidden\" id=\"viewing_user_feed\" name=\"viewing_user_feed\" value=\"");
      out.print((String)request.getAttribute("viewing_user_tweets_username"));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" id=\"viewing_specific_tweet\" name=\"viewing_specific_tweet\" value=\"");
      out.print((String)request.getAttribute("viewing_specific_tweet_uuid"));
      out.write("\" />\r\n");
      out.write("\t");

	if((Boolean)request.getAttribute("logged_in") == true) {
		
      out.write("\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"logged_in_user\" name=\"logged_in_user\" value=\"");
      out.print(logged_in_user.getUser());
      out.write("\" />\r\n");
      out.write("\t\t");

	} else {
		
      out.write("\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"logged_in_user\" name=\"logged_in_user\" value=\"0\" />\r\n");
      out.write("\t\t");

	}
	
      out.write("\r\n");
      out.write("\t<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script>window.jQuery || document.write('<script src=\"/test1/js/libs/jquery-1.10.1.min.js\"><\\/script>')</script>\r\n");
      out.write("\t<script src=\"/test1/js/libs/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"/test1/js/libs/date.format.js\"></script>\r\n");
      out.write("\t<script src=\"/test1/js/main.js\"></script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
